/* Games — content from replaymasters.eu/games. Images stay on replaymasters.eu. */
window.GAMES = [
{t:"ECTO-TERMINATOR 20000",th:"/media/yootheme/cache/18/GameEchoTerminator20000-18544837.png",by:"By Angela Wu, Henrique Moraes, Maria José Vargas Romero and Tomás Franco.",play:"https://sphodromantis.itch.io/ecto-terminator-20000",v:"AQpJAdmKuac",im:["GameEchoTerminator20000a.png","GameEchoTerminator20000b.png","GameEchoTerminator20000c.png"]},
{t:"Plug n' Panic",th:"/media/yootheme/cache/88/Plug01-88585ea0.png",by:"By Nathaly Kalantar, Néd Richard, Anastasiia Pershyna and Sirui Dong.",p:["An Alternative Controller game created for the module Playful Lab (2025)."],links:[["Game Play Video","https://www.youtube.com/watch?v=QRToKLrQ7uY"]],v:"QRToKLrQ7uY",im:["Plug02.png","Plug03.png","Plug04.png","Plug05.png"]},
{t:"Monster Briefcase",th:"/media/yootheme/cache/07/monster-briefcase-thumb-07b92091.jpg",by:"By Osman Gelmez, Talha Ahmed and EiZi Yu.",play:"https://talha651.itch.io/monster-breifcase",v:"sEa6UfGUyr0",im:["monster-briefcase-01.jpg","monster-briefcase-02.jpg","monster-briefcase-03.jpg","monster-briefcase-04.jpg","monster-briefcase-05.jpg"]},
{t:"Nobody",th:"/media/yootheme/cache/d2/nobody-thumb2-d2170e93.png",by:"By Conor Mulgrew, Yulia Krasova, Murtaza Imran, Lucia Tang Ya and Pauline Scherer.",play:"https://paupyro.itch.io/nobody",v:"tVhk5_dKEBg",im:["nobody-01.png","nobody-02.png","nobody-03.png","nobody-04.png","nobody-05.png"]},
{t:"Let me In!",th:"/media/yootheme/cache/bd/let%20me%20in%20thumb-bda164f5.png",by:"By Néd Richard, Anastasiia Pershyna, Helena Mongim and Dalia Safar.",play:"https://mikaexee.itch.io/let-me-in",im:["let%20me%20in%2001.png","let%20me%20in%2002.png","let%20me%20in%2003.png","let%20me%20in%2004.png"]},
{t:"Pressure Line",th:"/media/yootheme/cache/d5/pressure%20line%20thumb-d5bd83db.png",by:"By Conor Mulgrew, Henrique Souza Moraes, Osman Gelmez and Yulia Krasova.",play:"https://monkey-zebra-productions.itch.io/pressure-line",im:["pressure%20line%2001.png"]},
{t:"The Jam Game",th:"/media/yootheme/cache/72/jam%20game%20thumb-72f7aff8.png",by:"By Angela Wu, EiZi Yu and Sirui Dong.",play:"https://unsame.itch.io/the-jam-game",im:["jam%20game%2001.gif"]},
{t:"Crash Duck",th:"/media/yootheme/cache/84/crash%20duck%20thumb-84ead635.png",by:"By Nathaly Kalantar, Murtaza Imran, Tomás Franco and Talha Ahmed.",play:"https://nathkalantar.itch.io/crash-duck",im:["crach%20duck%2001.png"]},
{t:"Precrna Rupa",th:"/media/yootheme/cache/32/Precrna%20Rupa%20thumb-32731ddb.png",by:"By Maja Milas.",play:"https://mayazmaya.itch.io/precrna-rupa",v:"lg4C4DgqWiA",im:["Precrna%20Rupa%2001.png","Precrna%20Rupa%2002.png","Precrna%20Rupa%2003.png"]},
{t:"In Search of Lost Calls",th:"/media/yootheme/cache/36/in%20search%20of%20lost%20calls%20thumb-36616ff0.jpg",by:"By Amirhosein Khalil Zadeh and Fatemeh Norouzi.",play:"https://amir27.itch.io/in-search-of-lost-calls",v:"Nan6enz8O-Y",im:["in%20search%20of%20lost%20calls%2001.jpg","in%20search%20of%20lost%20calls%2002.jpg","in%20search%20of%20lost%20calls%2003.jpg","in%20search%20of%20lost%20calls%2004.jpg","in%20search%20of%20lost%20calls%2005.jpg"]},
{t:"Journey of Survival (JOS)",th:"/media/yootheme/cache/e7/jos%20thumb-e74f5f71.png",by:"By Samuel Chimezie Okeke and Hasib Hasan.",play:"https://chimex.itch.io/jos-journey-of-survival",im:["jos%2001.png","jos%2002.png","jos%2003.png","jos%2004.png","jos%2005.png","jos%2006.png"]},
{t:"South to North",th:"/media/yootheme/cache/6b/south%20to%20north%20thumb-6becaf8d.png",by:"By Aghababa Baghirov.",play:"https://aghababart.itch.io/south-to-north",v:"FuNME-aygsU",im:["south%20to%20north%2001.png"]},
{t:"Leapbound",th:"/media/yootheme/cache/f9/leapbound%20thumb-f9241e45.jpg",by:"By Olzhas Amanzhol, Osman Gelmez and Farhan Hashid.",play:"https://balabrola.itch.io/leapbound",im:["leapbound%2001.jpg","leapbound%2002.jpg","leapbound%2003.jpg"]},
{t:"Lost in Clouds",th:"/media/yootheme/cache/55/lost%20in%20clouds%20thumb-557b6ab4.png",by:"By Tomás Franco, Angela Wu, Lucia Tang Ya, Anastasiia Pershyna.",play:"https://sphodromantis.itch.io/lost-in-cloud",v:"0GCn4wEdFAs",im:["lost%20in%20clouds%2001.png","lost%20in%20clouds%2002.png","lost%20in%20clouds%2003.png","lost%20in%20clouds%2004.png"]},
{t:"The Hot Dog",th:"/media/yootheme/cache/b3/hotdog%20thumb-b36b7803.png",by:"By Nathaly Kalantar, Helena Mongim, Henrique Souza Moraes and Pauline Scherer.",p:["Ketchup: it's a dash.","Mustard: it's a jetpack."],play:"https://nathkalantar.itch.io/the-hot-dog",im:["hotdog%2001.png","hotdog%2002.png","hotdog%2003.png","hotdog%2004.png","hotdog%2005.png","hotdog%2006.png"]},
{t:"Kidung Rangda",th:"/media/yootheme/cache/c6/OiurRX-c6a7b685.jpg",by:"By Diandra Kathyusha Herli, Janne Denesse Ramos Nedamo and Prashik Sanjaykumar Chavan.",p:["A board game created for the module Play in Context: Personal in 2025."],q:["The module was all about designing a game that has deep ties to our cultures. For this particular project, we decided to cover our shared cultural superstitions and our shared interest for dark magic in Asia.","At first, we were lost in direction as we focused on the 'evil' aspect of dark magic and had difficulties designing a horror experience, but halfway through we realized we were completely ignoring the 'cultural' part of the exercise. After a bit of research, we rediscovered our roots and figured that black magic in Asian context is not about evil, but about misunderstood healing and worship.","Despite the tight deadline caused by us losing sight, we managed to pull through with a board game that we are extremely proud of. We managed to pull off design, balancing, and production of the physical pieces in a span of a week. But before we could do that, we suffered through failure nd learning for 3 weeks in order to be able to do everything in a few days.","((just as a side note, we have a super fancy video so please check it out!!))"],play:"https://sukinichi.itch.io/kidung-rangda",v:"ZnPhiBX_WVs",im:["bvVoK1.png","ZZfqzd.png"]},
{t:"Around The World",th:"/media/yootheme/cache/19/Around%20the%20World-19c9e9bc.png",by:"By Muhammad Arya Rakha, Samuel Chimezie Okeke, Diandra Kathyusha Herli, Ruobing Du and Soham Sen.",p:["An alternative-controller educational game created for the Experimental Play Lab in 2024."],play:"https://nuclearcactus.itch.io/around-the-world",v:"a8aPyiNFK6I",im:["jogo8.png","jogo8_2.png","jogo8_3.png"]},
{t:"Disquiet Time",th:"/media/yootheme/cache/26/disquiet%20time-26fbc8b8.png",by:"By Aghababa Baghirov.",p:["An alternative-controller puzzle-adventure game created at the Óbidos Game Jam for the Experimental Play Lab in 2024."],play:"https://aghababart.itch.io/disquiet-time",v:"H9HaxZFY8jw",im:["jogo10.png","jogo10_1.png","jogo10_2.png"]},
{t:"Omen",th:"/media/yootheme/cache/bf/omen-bf8df562.png",by:"By Ruobing Du.",p:["A Bitsy visual novel created for the Experimental Play Lab in 2024."],play:"https://ruobingdu.itch.io/omen",im:["jogo4_1.png","jogo4_2.png","jogo4_3.png"]},
{t:"Why Games?",th:"/media/yootheme/cache/6c/why%20games-6c865bee.png",by:"By Muhammad Arya Rakha.",p:["A Bitsy interactive fiction created for the Experimental Play Lab in 2024."],play:"https://arrakh.itch.io/why-games",im:["jogo3_1.png","jogo3_2.png","jogo3_3.png"]},
{t:"Three Layers of Limbo",th:"/media/yootheme/cache/9c/three%20layers%20of%20limbo-9cd54a41.png",by:"By Diandra Kathyusha Herli.",p:["A Bitsy interactive fiction created for the Experimental Play Lab in 2024."],play:"https://diandrakathyusha.itch.io/three-layers-of-limbo",im:["jogo2_1.png","jogo2_2.png","jogo2_3.png"]}
];
